### PR TITLE
Small improvements and bug fixes

### PR DESCRIPTION
**Pull request by tdanyluk**

### CODE REVIEW

**Comment by tdanyluk** [comment]
Hi! Would you please consider accepting these changes? I have a few other bigger changes in the pipeline which I could upload.

**Comment by frankrolf** [comment]
Thanks for your work! I am just seeing this (thanks GitHub), I will have a look and merge ASAP 😊

**Comment by tdanyluk** [comment]
Sg, thanks. :-)

**Comment by frankrolf** [comment]
Thank you so much for these fixes, and also thanks for fixing my spelling/weird grammar!
I am happy to see the code I wrote a decade ago is still in use ☺️

**Pull request merged**
